version: 2
    
jobs:
  deploy:
    docker:
      - image: circleci/node:11.11.0
      
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "Mine77@users.noreply.github.com"
            git config --global user.name "Mine77"
            echo "machine github.com login Mine77 password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=Mine77 yarn run publish-gh-pages
    
workflows:
  version: 2
  build:
    jobs:
      - deploy
      